stakater/Reloader

README.md
docs/How-it-works.md

This PR provides the solution to the issue mentioned [here](https://github.com/stakater/Reloader/issues/5)

[STK-322] Add How it works doc

---

README.md
docs/Reloader-vs-k8s-trigger-controller.md

This PR refers to the issue mentioned [here](https://github.com/stakater/Reloader/issues/6)

[STK-322] Add reloader vs k8s-trigger-controller doc

---

docs/Verify-Reloader-Working.md

Add doc how to verify reloader working

---

docs/features.md

this doc will/might help users to find this git repo and use it

create a feature docs for seo purposes

---

LICENSE
README.md

- add acknowledgements section
- configmap or secret name doesn't need to be same as deployment name

cleanup readme

---

README.md

Update readme about how to define multiple configmaps and secrets

---

README.md

Fix annotation placement confusion in readme

---

README.md
docs/How-it-works.md

Update readme and docs

---

README.md

Update readme to explain annotation position

---

internal/pkg/cmd/reloader.go
internal/pkg/controller/controller.go

Update start controller log

---

deployments/kubernetes/chart/reloader/templates/deployment.yaml
internal/pkg/callbacks/rolling_upgrade.go
internal/pkg/handler/upgrade.go
internal/pkg/handler/upgrade_test.go
internal/pkg/testutil/kube.go

Initial implementation for init container support

---

internal/pkg/handler/create.go
internal/pkg/handler/update.go
internal/pkg/handler/upgrade.go

fix-config-change-logs-issue 

---

README.md
internal/pkg/handler/upgrade.go

Initial implementation of fix for issue 61

---

README.md
deployments/kubernetes/chart/reloader/templates/deployment.yaml
deployments/kubernetes/chart/reloader/values.yaml
deployments/kubernetes/templates/chart/values.yaml.tmpl

add-node-selector-support

---

deployments/kubernetes/chart/reloader/Chart.yaml
deployments/kubernetes/chart/reloader/templates/deployment.yaml
deployments/kubernetes/chart/reloader/values.yaml
deployments/kubernetes/templates/chart/values.yaml.tmpl

These values are all empty by default.

Permit passing resources, tolerations, affinity to Helm chart

---

deployments/kubernetes/chart/reloader/templates/deployment.yaml

fix deployment template. Custom annotations check causing the ignore-resources field addition to fail

fix-deployment-template

---

deployments/kubernetes/chart/reloader/templates/_helpers.tpl
deployments/kubernetes/chart/reloader/templates/clusterrole.yaml
deployments/kubernetes/chart/reloader/templates/clusterrolebinding.yaml
deployments/kubernetes/chart/reloader/templates/deployment.yaml
deployments/kubernetes/chart/reloader/templates/role.yaml
deployments/kubernetes/chart/reloader/templates/rolebinding.yaml
deployments/kubernetes/chart/reloader/values.yaml
deployments/kubernetes/manifests/deployment.yaml

fix for default value issue for the service account
close #79

fix-issue-79

---

README.md

update the README.md by adding the info to replace the RELEASE-NAME with a proper value

add-info-for-manifest-issue

---

Jenkinsfile

- update Jenkinsfile by changing the pipeline library.
fixes #92

[fix-direct-installation-issue] update Jenkinsfile

---

README.md

update the vanilla manifest usage guidelines

fix-vanilla-manifest-usage-guideline

---

deployments/kubernetes/chart/reloader/templates/deployment.yaml
deployments/kubernetes/chart/reloader/templates/serviceaccount.yaml
deployments/kubernetes/chart/reloader/values.yaml

Signed-off-by: Marcos Estevez <marcos.stvz@gmail.com>

Sync with upstream helm/charts/stable/reloader

---

README.md
internal/pkg/cmd/reloader.go
internal/pkg/controller/controller.go
internal/pkg/controller/controller_test.go

Opened in replacement for #95 
Fixed test cases and refactored code a little bit

Add support for ignoring namespaces

---

README.md
internal/pkg/callbacks/rolling_upgrade.go
internal/pkg/testutil/kube.go

Make reloader compatible with kubernetes 1.16

---

deployments/kubernetes/chart/reloader/templates/role.yaml

fix value for helm template

---

internal/pkg/handler/upgrade.go
internal/pkg/handler/upgrade_test.go
internal/pkg/testutil/kube.go

This PR will support configmap/secret as source of projected volume
Fix #140

Support projected volume

---

deployments/kubernetes/chart/reloader/templates/deployment.yaml
deployments/kubernetes/manifests/deployment.yaml
deployments/kubernetes/reloader.yaml

Remove empty fields from kustomize deployment

---

deployments/kubernetes/chart/reloader/templates/deployment.yaml

Fixes the issue where setting the watchGlobally flag alone doesn't work.

Fix watch global

---

internal/pkg/testutil/kube.go

Code format via `gofmt -l -w -s .`
Signed-off-by: Liu Ming <hit_oak_tree@126.com>

style: gofmt -l -w -s .

---

pkg/kube/client.go

Polishing code...
Signed-off-by: Liu Ming <hit_oak_tree@126.com>

Polishing code

---

README.md
deployments/kubernetes/chart/reloader/templates/clusterrole.yaml
deployments/kubernetes/chart/reloader/templates/clusterrolebinding.yaml
deployments/kubernetes/chart/reloader/templates/role.yaml
deployments/kubernetes/chart/reloader/templates/rolebinding.yaml
deployments/kubernetes/chart/reloader/values.yaml
deployments/kubernetes/manifests/clusterrole.yaml
deployments/kubernetes/manifests/clusterrolebinding.yaml
deployments/kubernetes/reloader.yaml

Fix#169 - Update Rbac api versions

---

README.md
deployments/kubernetes/chart/reloader/templates/_helpers.tpl
deployments/kubernetes/chart/reloader/templates/clusterrole.yaml
deployments/kubernetes/chart/reloader/templates/clusterrolebinding.yaml
deployments/kubernetes/chart/reloader/templates/deployment.yaml
deployments/kubernetes/chart/reloader/templates/role.yaml
deployments/kubernetes/chart/reloader/templates/rolebinding.yaml
deployments/kubernetes/chart/reloader/templates/service.yaml
deployments/kubernetes/chart/reloader/templates/serviceaccount.yaml
docs/Helm2-to-Helm3.md

- Updated documentation to support Helm3
- Added the label `app.kubernetes.io/managed-by: "helm"` for each Reloader yaml manifest via _helpers.tpl
- Added following annoations for each Reloader yaml manifest via _helpers.tpl
```yaml
meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
meta.helm.sh/release-name: {{ .Release.Name | quote }}
```

Fix issue 173

---

deployments/kubernetes/chart/reloader/templates/serviceaccount.yaml
deployments/kubernetes/chart/reloader/values.yaml
deployments/kubernetes/templates/chart/values.yaml.tmpl

Add custom annotation support in service account

---

deployments/kubernetes/chart/reloader/templates/clusterrole.yaml
deployments/kubernetes/chart/reloader/templates/role.yaml

fix: read isArgoRollouts correctly in Helm chart

---

deployments/kubernetes/chart/reloader/templates/deployment.yaml
deployments/kubernetes/chart/reloader/values.yaml

Simple change to add priority class name to the helm chart.

Add priority class name to helm chart

---

deployments/kubernetes/chart/reloader/templates/deployment.yaml

Fixes error created by #263 in the deployment manifest

Fix yaml error in deployment manifest

---

deployments/kubernetes/chart/reloader/templates/deployment.yaml
deployments/kubernetes/chart/reloader/templates/serviceaccount.yaml

Add .Release.Namespace

---

deployments/kubernetes/chart/reloader/templates/deployment.yaml
deployments/kubernetes/chart/reloader/values.yaml
deployments/kubernetes/templates/chart/values.yaml.tmpl

Add replicas to helm-chart config. Issue: #289

add replicas config to helm-chart

---

.github/workflows/pull_request.yaml
.github/workflows/push.yaml

Update golang-cli package versions

---

.github/workflows/pull_request.yaml

Remove docker linting from Pull request

---

.github/workflows/pull_request.yaml
.vale.ini
README.md

Remove spell-checker

---

deployments/kubernetes/chart/reloader/templates/service.yaml

Set the namespace for the service

---

deployments/kubernetes/manifests/deployment.yaml

removed extra space in the yaml

extra space removed

---

okteto.yml

Hi :wave: I'm one of the developers of Okteto and I :heart:  to see this project use it.
I've updated the `okteto.yaml` manifest to v2 and added some minor improvements

Upgrade okteto yaml manifest to v2

---

internal/pkg/controller/controller.go

Fixes https://github.com/stakater/Reloader/issues/357

Update log level

---

.github/workflows/pull_request.yaml
.github/workflows/push.yaml

Update helm version in pipeline

---

README.md
deployments/kubernetes/chart/reloader/templates/deployment.yaml
deployments/kubernetes/chart/reloader/values.yaml
internal/pkg/cmd/reloader.go
internal/pkg/controller/controller.go
internal/pkg/options/flags.go

- Add sync after restart functionality
- Fixes an issue where controller was not properly initialized

Implement sync after restart

---

deployments/kubernetes/chart/reloader/templates/deployment.yaml
deployments/kubernetes/chart/reloader/values.yaml

This PR add the ability to deploy on multiple area with high availability
Fix: https://github.com/stakater/Reloader/issues/426

✨ feat: Implement topologySpreadConstraints to improve redundancy (fix #426)

---

README.md

The pipeline for push to master might be misfiring, doing a minor update to test it after approval and merge

Enterprise update

---

.github/workflows/pull_request.yaml

Link check is removed - it is done as part of QA template

Helm chart unit tests

---

README.md

Update the compatibility section of readme file fixing the kubernetes requirements from 1.9 to 1.19

Update the README file 

---

.github/workflows/push.yaml

Revert "Modify ghcr login to use stakater token instead of user token"

---

.github/workflows/pull_request.yaml
.github/workflows/push.yaml
Dockerfile.ubi

https://github.com/stakater/Reloader/issues/348
Made a start on this, I'm sure changes will be needed so let me know and I will try to get this over the line.

add ubi dockerfile

---

README.md

See #600 
Fixes #600 
Update documentation for `reloadOnCreate` and `syncAfterRestart` within the Readme file.

Issue/600 - [BUG] Reloader don't restart pod on secret recreation

---

deployments/kubernetes/chart/reloader/templates/verticalpodautoscaler.yaml
deployments/kubernetes/chart/reloader/values.yaml

This PR adds support the the vertical pod autoscaler so users do not have to care about the resource usage of application and let the vertical pod autoscaler to do its job.

feat(chart): add vpa support

---

deployments/kubernetes/chart/reloader/values.yaml

fix: Add seccompProfile type to default securityContext

---

internal/pkg/cmd/reloader.go
internal/pkg/options/flags.go

Statement
See https://github.com/stakater/Reloader/issues/631
Related Issue
Fixes https://github.com/stakater/Reloader/issues/631

feat: supports --log-level argument  in command line

---

docs/Helm2-to-Helm3.md
docs/How-it-works.md
docs/Reloader-vs-k8s-trigger-controller.md
docs/Verify-Reloader-Working.md

Capitalize headings
See if https://github.com/stakater/Reloader/issues/649 is triggered, because it was caused by https://github.com/stakater/Reloader/pull/648, so either doc updates causes the issue, or it is a fluke with the tag action

Make trivial doc updates

---

.gitignore

Not sure why the yq binary is in this repo?

chore: delete yq binary from repo

---

.github/workflows/release.yaml

https://github.com/goreleaser/goreleaser/blob/8244d52f08bdcdd5b410a76a37507e3985cf64bf/www/docs/deprecations.md?plain=1#L454

Update goreleaser with --clean flag

---

README.md

This PR contains the feature "reload-on-delete" as documentation in README.md according to PR https://github.com/stakater/Reloader/pull/695 about issue https://github.com/stakater/Reloader/issues/622.
@MuneebAijaz

feature "reload-on-delete" documented in README.md

---

README.md

A couple small whitespace fixups in README

A couple small whitespace fixups in README

---

.github/workflows/reloader-enterprise.yml

Add pipeline trigger for Reloader enterprise.

Reloader Enterprise

---

.github/workflows/pull_request.yaml

Switch PR workflow from `pull_request_target` to `pull_request` and remove the usage of secrets

Switch PR workflow to pull_request

---

internal/pkg/handler/upgrade.go

issues were reported in logrus as part of [this](https://github.com/stakater/Reloader/actions/runs/10293325025/job/28747027087?pr=724). This PR fixes it.

fixing go vet issues with logrus

---

deployments/kubernetes/reloader.yaml

Increasing memory for plain manifests to not cause issues on installation

Increase memory for plain manifest

---

.github/workflows/pull_request_docs.yaml
README.md
deployments/kubernetes/chart/reloader/README.md

Move the content of the Helm chart from the repository README to its own chart README

Move Helm docs to its own chart README

---

deployments/kubernetes/chart/reloader/templates/clusterrole.yaml
deployments/kubernetes/chart/reloader/values.yaml

Related issue: https://github.com/stakater/Reloader/issues/866

#866: Security ClusterRole - Helm Chart

---

README.md

little bit of restructuring

---

deployments/kubernetes/chart/reloader/Chart.yaml
deployments/kubernetes/chart/reloader/templates/_helpers.tpl
deployments/kubernetes/chart/reloader/templates/deployment.yaml
deployments/kubernetes/chart/reloader/templates/networkpolicy.yaml
deployments/kubernetes/chart/reloader/templates/poddisruptionbudget.yaml

For https://github.com/stakater/Reloader/issues/897

Revert chart labels for seamless upgrades

---

deployments/kubernetes/chart/reloader/Chart.yaml
deployments/kubernetes/chart/reloader/values.yaml

For https://github.com/stakater/Reloader/releases/tag/v1.4.2

Update Helm chart for v1.4.2

---

internal/pkg/handler/pause_deployment.go
internal/pkg/handler/pause_deployment_test.go
internal/pkg/handler/upgrade.go
internal/pkg/handler/upgrade_test.go
internal/pkg/options/flags.go
internal/pkg/testutil/kube.go

This PR implements https://github.com/stakater/Reloader/issues/837 and is an updated version of the following PR https://github.com/stakater/Reloader/pull/838

Add pausing deployments during upgrades

---

deployments/kubernetes/chart/reloader/README.md
deployments/kubernetes/chart/reloader/values.yaml

Fixes issue: [Issue Link](https://github.com/stakater/Reloader/issues/975)
Updated Readme.md within charts directory.
Thanks to @msafwankarim

Moved Voume & VoumeMounts within Deployment in values.yaml

---

deployments/kubernetes/chart/reloader/Chart.yaml
deployments/kubernetes/chart/reloader/README.md
deployments/kubernetes/chart/reloader/templates/deployment.yaml
deployments/kubernetes/chart/reloader/values.yaml

See: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config

reloader: Add in support for dnsConfig for pod reloader.
